-- MySQL Script generated by MySQL Workbench
-- Tue Apr 10 19:50:54 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`agent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`agent` ;

CREATE TABLE IF NOT EXISTS `mydb`.`agent` (
  `id_agent` INT NOT NULL,
  `photoAgent` VARCHAR(45) NULL,
  `nomAgent` VARCHAR(45) NULL,
  `prenomAgent` VARCHAR(45) NULL,
  `villeAffectationAgent` VARCHAR(45) NULL,
  `mailAgent` VARCHAR(45) NULL,
  `numeroTelephoneAgent` INT NULL,
  PRIMARY KEY (`id_agent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`logement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`logement` ;

CREATE TABLE IF NOT EXISTS `mydb`.`logement` (
  `id_logement` INT NOT NULL,
  `photoLogement` VARCHAR(45) NULL,
  `villeLogement` VARCHAR(45) NULL,
  `chambreLogement` TINYINT NULL,
  `salleDeBainLogement` TINYINT NULL,
  `toilettesLogement` TINYINT NULL,
  `cuisineLogement` TINYINT NULL,
  `sejourLogement` TINYINT NULL,
  `dateDispoDebutLogement` DATE NULL,
  `dateDispoFinLogement` DATE NULL,
  `prixLogement` INT NULL,
  `agent_id_agent` INT NOT NULL,
  PRIMARY KEY (`id_logement`),
  INDEX `fk_logement_agent_idx` (`agent_id_agent` ASC),
  CONSTRAINT `fk_logement_agent`
    FOREIGN KEY (`agent_id_agent`)
    REFERENCES `mydb`.`agent` (`id_agent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
